### ISSUE TITLE
get_vectors seems not released

### ISSUE THREAD

**Issue by Alexanderisgod** [TonyXuQAQ/CenterLineDet#1]
![2022-10-25 16-15-23 的屏幕截图](https://user-images.githubusercontent.com/41862202/197720657-6b32c916-9a99-4fda-b02c-795707656c9b.png)

**Comment by TonyXuQAQ** [comment]
Hi,

This function is defined and used in [HDMapNet](https://github.com/Tsinghua-MARS-Lab/HDMapNet) and this repo reuses some codes of HDMapNet. However, ```get_vectors``` is never called in CenterLineDet. We apologize for not well cleaning the code.

Please report any bugs by opening an issue.
