### ISSUE TITLE
AttributeError: 'NuScenesMap' object has no attribute 'get_graph'

### ISSUE THREAD

**Issue by xinfu607** [TonyXuQAQ/CenterLineDet#3]
root@cb61bb1e359f:/xinfu/CenterLineDet/data# python get_map_json_label.py
Traceback (most recent call last):
  File "get_map_json_label.py", line 91, in <module>
    graph_list = nusc_map.get_graph(resolution_meters=1)
AttributeError: 'NuScenesMap' object has no attribute 'get_graph'

The AttributeError comes when running "python get_map_json_label.py". Would you please let me know the reason. Thanks a lot.

**Comment by TonyXuQAQ** [comment]
```get_graph``` is a customized function which is defined [here](https://github.com/TonyXuQAQ/CenterLineDet/blob/master/nuscenes/map_expansion/map_api.py#:~:text=def%20get_graph(self%2C%20resolution_meters%3A%20float)%20%2D%3E%20List%5Bnp.array%5D%3A). And in this repo the nuscenes toolkit is different from the official nuscenes toolkit. Make sure you import the nuscenes toolkit provided in this repo.

**Comment by xinfu607** [comment]
Thanks a lot.
