### ISSUE TITLE
Train for base segmentation model

### ISSUE THREAD

**Issue by TmacTmac1992** [TonyXuQAQ/CenterLineDet#4]
Hi, Thanks for open source the code. Can you please provide the checkpoint of FusionNet_for_CenterLineDet and HDMapNet_for_CenterLineDet?

**Comment by TonyXuQAQ** [comment]
Sorry for the late reply. I have left the previous research group and I am not able to access the data saved on the server.

FusionNet_for_CenterLineDet/HDMapNet_for_CenterLineDet are only used during training, and they are not used for inference. They are trained on half of the training set to handle the overfitting segmentation problem during the training period. You can train your own checkpoints by running the provided scripts.

Apologize for any caused inconvenience.
