### ISSUE TITLE
How to get the gt centerlines

### ISSUE THREAD

**Issue by xiaolul2** [TonyXuQAQ/CenterLineDet#5]
Thanks for your excellent work！
I want to know how you got the gt centerlines of the maps. Did you calculate them by the boundaries or use other auxiliary tools?
Thanks again for your reply!

**Comment by TonyXuQAQ** [comment]
Thanks for the question. The GT centerlines are directly converted from the HD map provided by the NuScenes dataset. You could also find the provided HD map from the Argoverse dataset.
