### ISSUE TITLE
segmentation_baselines train file miss。

### ISSUE THREAD

**Issue by wheelandwheat** [TonyXuQAQ/CenterLineDet#6]
hi，
    Thanks for sharing your code，I read the readme in folder “segmentation_baselines”，and found there is no train.py to train segmentation_baselines，Look forward to your favourable reply。

**Comment by TonyXuQAQ** [comment]
Thanks for the issue report. Sorry that we forgot to change the ```.gitignore``` and the segmentation train script is ignored. The problem is fixed and it should work now.
